[2024-08-03T09:05:24.919+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:05:24.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:05:24.922+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:05:24.922+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:05:24.967+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:05:24.964+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:05:24.969+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:05:25.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.088 seconds
[2024-08-03T09:05:55.466+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:05:55.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:05:55.470+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:05:55.469+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:05:55.490+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:05:55.486+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:05:55.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:05:55.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T09:06:31.841+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:06:31.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:06:31.845+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:06:31.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:06:31.862+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:06:31.858+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:06:31.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:06:31.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.056 seconds
[2024-08-03T09:07:02.503+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:07:02.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:07:02.506+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:07:02.506+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:07:02.525+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:07:02.521+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:07:02.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:07:02.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.048 seconds
[2024-08-03T09:55:53.120+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:55:53.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:55:53.127+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:55:53.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:55:53.445+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:55:53.441+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:55:53.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:55:53.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.387 seconds
[2024-08-03T09:56:23.588+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:56:23.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:56:23.592+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:56:23.592+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:56:23.610+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:56:23.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:56:23.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:56:23.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.050 seconds
[2024-08-03T09:56:54.053+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:56:54.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:56:54.056+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:56:54.055+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:56:54.069+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:56:54.066+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:56:54.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:56:54.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.041 seconds
[2024-08-03T09:57:24.670+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:57:24.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:57:24.673+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:57:24.673+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:57:24.691+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:57:24.687+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:57:24.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:57:24.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T09:57:55.241+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:57:55.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:57:55.244+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:57:55.244+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:57:55.260+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:57:55.256+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:57:55.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:57:55.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.045 seconds
[2024-08-03T09:58:25.717+0000] {processor.py:161} INFO - Started process (PID=349) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:58:25.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:58:25.720+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:58:25.719+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:58:25.736+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:58:25.732+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:58:25.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:58:25.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.046 seconds
[2024-08-03T09:58:56.041+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:58:56.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:58:56.044+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:58:56.044+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:58:56.062+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:58:56.058+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:58:56.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:58:56.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.050 seconds
[2024-08-03T09:59:26.516+0000] {processor.py:161} INFO - Started process (PID=467) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:59:26.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:59:26.520+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:59:26.519+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:59:26.536+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:59:26.533+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:59:26.538+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:59:26.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.047 seconds
[2024-08-03T09:59:56.989+0000] {processor.py:161} INFO - Started process (PID=526) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T09:59:56.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T09:59:56.992+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:59:56.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:59:57.008+0000] {logging_mixin.py:188} INFO - [2024-08-03T09:59:57.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T09:59:57.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T09:59:57.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.048 seconds
[2024-08-03T10:00:27.622+0000] {processor.py:161} INFO - Started process (PID=585) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:00:27.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:00:27.627+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:00:27.627+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:00:27.643+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:00:27.640+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:00:27.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:00:30.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 2.519 seconds
[2024-08-03T10:01:00.205+0000] {processor.py:161} INFO - Started process (PID=644) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:01:00.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:01:00.208+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:01:00.208+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:01:00.225+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:01:00.221+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:01:00.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:01:00.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.046 seconds
[2024-08-03T10:01:30.406+0000] {processor.py:161} INFO - Started process (PID=703) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:01:30.407+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:01:30.410+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:01:30.410+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:01:30.427+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:01:30.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:01:30.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:01:30.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.045 seconds
[2024-08-03T10:02:00.693+0000] {processor.py:161} INFO - Started process (PID=780) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:02:00.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:02:00.697+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:02:00.697+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:02:00.711+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:02:00.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:02:00.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:02:00.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.043 seconds
[2024-08-03T10:02:30.914+0000] {processor.py:161} INFO - Started process (PID=839) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:02:30.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:02:30.917+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:02:30.917+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:02:30.934+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:02:30.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:02:30.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:02:31.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.175 seconds
[2024-08-03T10:03:01.578+0000] {processor.py:161} INFO - Started process (PID=898) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:03:01.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:03:01.582+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:03:01.581+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:03:01.597+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:03:01.594+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:03:01.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:03:01.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.043 seconds
[2024-08-03T10:03:31.707+0000] {processor.py:161} INFO - Started process (PID=958) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:03:31.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:03:31.710+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:03:31.709+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:03:31.727+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:03:31.723+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:03:31.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:03:31.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.046 seconds
[2024-08-03T10:04:02.092+0000] {processor.py:161} INFO - Started process (PID=1028) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:04:02.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:04:02.095+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:04:02.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:04:02.112+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:04:02.108+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:04:02.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:04:02.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.051 seconds
[2024-08-03T10:04:32.206+0000] {processor.py:161} INFO - Started process (PID=1087) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:04:32.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:04:32.210+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:04:32.209+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:04:32.228+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:04:32.224+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:04:32.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:04:32.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.047 seconds
[2024-08-03T10:05:02.680+0000] {processor.py:161} INFO - Started process (PID=1164) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:05:02.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:05:02.683+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:05:02.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:05:02.704+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:05:02.698+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:05:02.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:05:02.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.051 seconds
[2024-08-03T10:05:32.762+0000] {processor.py:161} INFO - Started process (PID=1223) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:05:32.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:05:32.765+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:05:32.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:05:32.782+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:05:32.779+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:05:32.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:05:32.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.046 seconds
[2024-08-03T10:06:03.058+0000] {processor.py:161} INFO - Started process (PID=1282) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:06:03.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:06:03.062+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:06:03.061+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:06:03.081+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:06:03.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:06:03.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:06:03.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.050 seconds
[2024-08-03T10:06:33.525+0000] {processor.py:161} INFO - Started process (PID=1341) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:06:33.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:06:33.528+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:06:33.527+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:06:33.544+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:06:33.541+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:06:33.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:06:33.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.047 seconds
[2024-08-03T10:07:03.747+0000] {processor.py:161} INFO - Started process (PID=1401) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:07:03.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:07:03.750+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:07:03.750+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:07:03.768+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:07:03.764+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:07:03.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:07:03.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.048 seconds
[2024-08-03T10:07:33.912+0000] {processor.py:161} INFO - Started process (PID=1460) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:07:33.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:07:33.916+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:07:33.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:07:33.934+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:07:33.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:07:33.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:07:33.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T10:08:04.028+0000] {processor.py:161} INFO - Started process (PID=1519) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:08:04.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:08:04.031+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:08:04.031+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:08:04.046+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:08:04.043+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:08:04.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:08:04.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.045 seconds
[2024-08-03T10:08:34.785+0000] {processor.py:161} INFO - Started process (PID=1578) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:08:34.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:08:34.789+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:08:34.788+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:08:34.810+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:08:34.805+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:08:34.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:08:34.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.057 seconds
[2024-08-03T10:09:05.034+0000] {processor.py:161} INFO - Started process (PID=1637) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:09:05.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:09:05.037+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:09:05.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:09:05.051+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:09:05.048+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:09:05.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:09:05.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.045 seconds
[2024-08-03T10:09:35.970+0000] {processor.py:161} INFO - Started process (PID=1700) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:09:35.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:09:35.973+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:09:35.973+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:09:35.988+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:09:35.985+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:09:35.989+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:09:36.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T10:10:06.576+0000] {processor.py:161} INFO - Started process (PID=1759) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:10:06.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:10:06.579+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:10:06.579+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:10:06.596+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:10:06.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:10:06.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:10:06.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.047 seconds
[2024-08-03T10:10:36.763+0000] {processor.py:161} INFO - Started process (PID=1818) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:10:36.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:10:36.766+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:10:36.766+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:10:36.784+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:10:36.781+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:10:36.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:10:36.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T10:11:07.407+0000] {processor.py:161} INFO - Started process (PID=1877) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:11:07.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:11:07.411+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:11:07.410+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:11:07.428+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:11:07.425+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:11:07.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:11:07.450+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T10:11:37.927+0000] {processor.py:161} INFO - Started process (PID=1936) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:11:37.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:11:37.930+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:11:37.929+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:11:37.945+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:11:37.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:11:37.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:11:37.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T10:12:08.942+0000] {processor.py:161} INFO - Started process (PID=1995) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:12:08.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:12:08.945+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:12:08.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:12:08.963+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:12:08.959+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:12:08.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:12:08.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.050 seconds
[2024-08-03T10:12:39.594+0000] {processor.py:161} INFO - Started process (PID=2054) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:12:39.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:12:39.598+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:12:39.598+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:12:39.616+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:12:39.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:12:39.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:12:39.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.052 seconds
[2024-08-03T10:13:09.909+0000] {processor.py:161} INFO - Started process (PID=2113) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:13:09.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:13:09.915+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:13:09.914+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:13:09.930+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:13:09.927+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:13:09.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:13:09.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.048 seconds
[2024-08-03T10:13:40.418+0000] {processor.py:161} INFO - Started process (PID=2172) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:13:40.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:13:40.422+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:13:40.422+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:13:40.440+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:13:40.437+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:13:40.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:13:40.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.055 seconds
[2024-08-03T10:14:10.596+0000] {processor.py:161} INFO - Started process (PID=2231) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:14:10.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:14:10.599+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:14:10.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:14:10.618+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:14:10.615+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:14:10.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:14:10.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.053 seconds
[2024-08-03T10:14:40.994+0000] {processor.py:161} INFO - Started process (PID=2290) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:14:40.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:14:40.997+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:14:40.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:14:41.016+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:14:41.012+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:14:41.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:14:41.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.053 seconds
[2024-08-03T10:15:11.316+0000] {processor.py:161} INFO - Started process (PID=2349) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:15:11.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:15:11.320+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:15:11.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:15:11.337+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:15:11.334+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:15:11.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:15:11.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.056 seconds
[2024-08-03T10:15:41.812+0000] {processor.py:161} INFO - Started process (PID=2408) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:15:41.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:15:41.815+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:15:41.815+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:15:41.832+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:15:41.828+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:15:41.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:15:41.855+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.053 seconds
[2024-08-03T10:16:12.611+0000] {processor.py:161} INFO - Started process (PID=2467) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:16:12.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:16:12.614+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:16:12.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:16:12.631+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:16:12.627+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:16:12.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:16:12.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.052 seconds
[2024-08-03T10:16:43.021+0000] {processor.py:161} INFO - Started process (PID=2526) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:16:43.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:16:43.024+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:16:43.024+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:16:43.044+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:16:43.039+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:16:43.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:16:43.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.052 seconds
[2024-08-03T10:17:13.290+0000] {processor.py:161} INFO - Started process (PID=2585) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:17:13.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:17:13.293+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:17:13.293+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:17:13.309+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:17:13.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:17:13.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:17:13.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.050 seconds
[2024-08-03T10:17:43.525+0000] {processor.py:161} INFO - Started process (PID=2644) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:17:43.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:17:43.528+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:17:43.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:17:43.543+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:17:43.540+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:17:43.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:17:43.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T10:18:13.770+0000] {processor.py:161} INFO - Started process (PID=2703) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:18:13.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:18:13.773+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:18:13.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:18:13.791+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:18:13.788+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:18:13.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:18:13.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.054 seconds
[2024-08-03T10:18:43.976+0000] {processor.py:161} INFO - Started process (PID=2762) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:18:43.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:18:43.980+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:18:43.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:18:43.998+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:18:43.994+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:18:44.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:18:44.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.052 seconds
[2024-08-03T10:19:14.192+0000] {processor.py:161} INFO - Started process (PID=2821) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:19:14.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:19:14.197+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:19:14.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:19:14.217+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:19:14.212+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:19:14.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:19:14.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.074 seconds
[2024-08-03T10:19:44.596+0000] {processor.py:161} INFO - Started process (PID=2880) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:19:44.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:19:44.600+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:19:44.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:19:44.621+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:19:44.617+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:19:44.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:19:44.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.057 seconds
[2024-08-03T10:20:14.942+0000] {processor.py:161} INFO - Started process (PID=2939) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:20:14.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:20:14.945+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:20:14.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:20:14.965+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:20:14.960+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:20:14.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:20:14.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.053 seconds
[2024-08-03T10:20:45.181+0000] {processor.py:161} INFO - Started process (PID=2998) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:20:45.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:20:45.185+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:20:45.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:20:45.202+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:20:45.199+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:20:45.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:20:45.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.052 seconds
[2024-08-03T10:21:15.663+0000] {processor.py:161} INFO - Started process (PID=3057) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:21:15.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:21:15.666+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:21:15.666+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:21:15.684+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:21:15.681+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:21:15.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:21:15.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.051 seconds
[2024-08-03T10:21:45.927+0000] {processor.py:161} INFO - Started process (PID=3116) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:21:45.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:21:45.930+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:21:45.930+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:21:45.948+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:21:45.945+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:21:45.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:21:45.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.054 seconds
[2024-08-03T10:22:16.285+0000] {processor.py:161} INFO - Started process (PID=3175) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:22:16.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:22:16.290+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:22:16.289+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:22:16.312+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:22:16.308+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:22:16.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:22:16.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.063 seconds
[2024-08-03T10:22:46.782+0000] {processor.py:161} INFO - Started process (PID=3234) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:22:46.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:22:46.785+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:22:46.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:22:46.805+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:22:46.800+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:22:46.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:22:46.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.053 seconds
[2024-08-03T10:23:17.118+0000] {processor.py:161} INFO - Started process (PID=3292) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:23:17.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:23:17.121+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:23:17.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:23:17.142+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:23:17.139+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:23:17.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:23:17.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.052 seconds
[2024-08-03T10:23:47.468+0000] {processor.py:161} INFO - Started process (PID=3351) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:23:47.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:23:47.473+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:23:47.472+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:23:47.494+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:23:47.490+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:23:47.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:23:47.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.072 seconds
[2024-08-03T10:24:17.846+0000] {processor.py:161} INFO - Started process (PID=3411) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:24:17.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:24:17.849+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:24:17.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:24:17.864+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:24:17.861+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:24:17.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:24:17.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T10:24:48.120+0000] {processor.py:161} INFO - Started process (PID=3470) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:24:48.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:24:48.123+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:24:48.123+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:24:48.143+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:24:48.140+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:24:48.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:24:48.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.052 seconds
[2024-08-03T10:25:18.621+0000] {processor.py:161} INFO - Started process (PID=3529) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:25:18.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:25:18.625+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:25:18.624+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:25:18.644+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:25:18.638+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:25:18.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:25:18.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.055 seconds
[2024-08-03T10:25:49.216+0000] {processor.py:161} INFO - Started process (PID=3588) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:25:49.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:25:49.220+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:25:49.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:25:49.244+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:25:49.241+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:25:49.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:25:49.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.069 seconds
[2024-08-03T10:26:19.753+0000] {processor.py:161} INFO - Started process (PID=3647) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:26:19.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:26:19.756+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:26:19.756+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:26:19.774+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:26:19.771+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:26:19.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:26:19.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.051 seconds
[2024-08-03T10:26:50.055+0000] {processor.py:161} INFO - Started process (PID=3706) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:26:50.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:26:50.059+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:26:50.059+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:26:50.078+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:26:50.074+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:26:50.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:26:50.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.061 seconds
[2024-08-03T10:27:20.580+0000] {processor.py:161} INFO - Started process (PID=3765) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:27:20.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:27:20.585+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:27:20.585+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:27:20.615+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:27:20.609+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:27:20.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:27:20.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.078 seconds
[2024-08-03T10:27:51.237+0000] {processor.py:161} INFO - Started process (PID=3824) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:27:51.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:27:51.241+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:27:51.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:27:51.261+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:27:51.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:27:51.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:27:51.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.062 seconds
[2024-08-03T10:28:21.522+0000] {processor.py:161} INFO - Started process (PID=3883) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:28:21.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:28:21.525+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:28:21.525+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:28:21.545+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:28:21.541+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:28:21.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:28:21.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.052 seconds
[2024-08-03T10:28:51.934+0000] {processor.py:161} INFO - Started process (PID=3942) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:28:51.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:28:51.938+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:28:51.937+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:28:51.960+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:28:51.956+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:28:51.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:28:51.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.061 seconds
[2024-08-03T10:29:22.176+0000] {processor.py:161} INFO - Started process (PID=4001) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:29:22.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:29:22.179+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:29:22.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:29:22.198+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:29:22.194+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:29:22.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:29:22.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.055 seconds
[2024-08-03T10:29:52.314+0000] {processor.py:161} INFO - Started process (PID=4060) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:29:52.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:29:52.318+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:29:52.317+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:29:52.334+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:29:52.330+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:29:52.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:29:52.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.054 seconds
[2024-08-03T10:30:22.595+0000] {processor.py:161} INFO - Started process (PID=4119) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:30:22.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:30:22.598+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:30:22.598+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:30:22.616+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:30:22.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:30:22.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:30:22.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.050 seconds
[2024-08-03T10:30:52.852+0000] {processor.py:161} INFO - Started process (PID=4178) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:30:52.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:30:52.855+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:30:52.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:30:52.872+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:30:52.869+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:30:52.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:30:52.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.050 seconds
[2024-08-03T10:31:23.488+0000] {processor.py:161} INFO - Started process (PID=4237) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:31:23.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:31:23.497+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:31:23.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:31:23.514+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:31:23.511+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:31:23.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:31:23.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.057 seconds
[2024-08-03T10:31:53.619+0000] {processor.py:161} INFO - Started process (PID=4296) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:31:53.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:31:53.623+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:31:53.622+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:31:53.639+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:31:53.637+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:31:53.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:31:53.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.054 seconds
[2024-08-03T10:32:23.852+0000] {processor.py:161} INFO - Started process (PID=4355) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:32:23.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:32:23.862+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:32:23.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:32:23.910+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:32:23.899+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:32:23.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:32:23.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.124 seconds
[2024-08-03T10:32:54.333+0000] {processor.py:161} INFO - Started process (PID=4415) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:32:54.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:32:54.336+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:32:54.336+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:32:54.363+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:32:54.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:32:54.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:32:54.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2024-08-03T10:33:24.513+0000] {processor.py:161} INFO - Started process (PID=4474) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:33:24.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:33:24.516+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:33:24.516+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:33:24.532+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:33:24.527+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:33:24.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:33:24.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.049 seconds
[2024-08-03T10:33:55.145+0000] {processor.py:161} INFO - Started process (PID=4532) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:33:55.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:33:55.150+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:33:55.150+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:33:55.179+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:33:55.170+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:33:55.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:33:55.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.085 seconds
[2024-08-03T10:34:25.590+0000] {processor.py:161} INFO - Started process (PID=4591) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:34:25.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:34:25.594+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:34:25.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:34:25.615+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:34:25.610+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:34:25.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:34:25.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.060 seconds
[2024-08-03T10:34:55.789+0000] {processor.py:161} INFO - Started process (PID=4650) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:34:55.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:34:55.793+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:34:55.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:34:55.812+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:34:55.808+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:34:55.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:34:55.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.064 seconds
[2024-08-03T10:35:26.214+0000] {processor.py:161} INFO - Started process (PID=4709) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:35:26.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:35:26.222+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:35:26.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:35:26.251+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:35:26.246+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:35:26.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:35:26.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.080 seconds
[2024-08-03T10:35:57.618+0000] {processor.py:161} INFO - Started process (PID=4767) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:35:57.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:35:57.625+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:35:57.624+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:35:57.645+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:35:57.640+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:35:57.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:35:57.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.083 seconds
[2024-08-03T10:36:28.118+0000] {processor.py:161} INFO - Started process (PID=4826) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:36:28.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:36:28.121+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:36:28.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:36:28.308+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:36:28.135+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:36:28.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:36:28.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.223 seconds
[2024-08-03T10:36:58.894+0000] {processor.py:161} INFO - Started process (PID=4885) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:36:58.896+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:36:58.898+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:36:58.898+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:36:58.919+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:36:58.914+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:36:58.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:36:59.014+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.132 seconds
[2024-08-03T10:37:29.718+0000] {processor.py:161} INFO - Started process (PID=4943) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:37:29.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:37:29.722+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:37:29.721+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:37:30.638+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:37:29.740+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:37:30.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:37:30.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 1.033 seconds
[2024-08-03T10:38:01.662+0000] {processor.py:161} INFO - Started process (PID=5002) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:38:01.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:38:01.665+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:38:01.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:38:01.688+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:38:01.682+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:38:01.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:38:01.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.061 seconds
[2024-08-03T10:38:32.232+0000] {processor.py:161} INFO - Started process (PID=5061) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:38:32.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:38:32.235+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:38:32.235+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:38:32.253+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:38:32.249+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:38:32.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:38:32.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.051 seconds
[2024-08-03T10:39:02.780+0000] {processor.py:161} INFO - Started process (PID=5120) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:39:02.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:39:02.783+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:39:02.782+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:39:02.800+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:39:02.797+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:39:02.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:39:02.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.054 seconds
[2024-08-03T10:39:32.919+0000] {processor.py:161} INFO - Started process (PID=5179) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:39:32.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:39:32.922+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:39:32.922+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:39:32.942+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:39:32.938+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:39:32.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:39:33.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.140 seconds
[2024-08-03T10:40:03.318+0000] {processor.py:161} INFO - Started process (PID=5238) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:40:03.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:40:03.335+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:40:03.332+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:40:03.372+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:40:03.364+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:40:03.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:40:03.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.212 seconds
[2024-08-03T10:53:47.043+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:53:47.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:53:47.048+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:53:47.047+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:53:47.113+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:53:47.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:53:47.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:53:47.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.114 seconds
[2024-08-03T10:54:18.040+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:54:18.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:54:18.044+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:54:18.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:54:18.061+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:54:18.057+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:54:18.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:54:18.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.055 seconds
[2024-08-03T10:54:48.284+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/hw_dag.py
[2024-08-03T10:54:48.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-08-03T10:54:48.294+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:54:48.289+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:54:48.321+0000] {logging_mixin.py:188} INFO - [2024-08-03T10:54:48.313+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 14, in <module>
    from modules.pipeline import pipeline
ModuleNotFoundError: No module named 'modules'
[2024-08-03T10:54:48.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-08-03T10:54:48.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.098 seconds
